// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipldxsnmecelhebazefx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwbGR4c25tZWNlbGhlYmF6ZWZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTYxMjgsImV4cCI6MjA2OTI5MjEyOH0.9bjTNIchcCp8lH0YHR9JcYlToFmiX_nC9f_js4ilCPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});